apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    app: nginx-app
  annotations:
    creator: Saumya
spec:
  volumes:
  - name: apphtml
    emptyDir: {}
  containers:
  - name: nginx
    image: nginx:alpine
    volumeMounts:
    - name: apphtml
      mountPath: /usr/share/nginx/html
      readOnly: true
  - name: alpine
    image: alpine
    command: ["/bin/sh", "-c"]
    args:
    - while true; do date >> /html/index.html; sleep 30; done;
    volumeMounts:
    - name: apphtml
      mountPath: /html
    ports:
        - containerPort: 80
    
    # k port-forward pod1 8080:80 



