apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod1
  namespace: ns1
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: busybox
    imagePullPolicy: ifNotPresent
    resources:
      limits:
        cpu: "1"
        #memory: "1000Gi"
      requests:
        cpu: "0.5"
        #memory: "1000Gi"
    command: ['sh', '-c', 'echo The app is running! && sleep 3']
    lifecycle:
      postStart:
        exec: 
          command: ["/bin/sh","-c","sleep 1"]
  restartPolicy: OnFailure 