apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
  namespace: ns1
  labels: 
    app : busybox-app
spec:
  containers:
  - name: busybox
    image: busybox
    resources:
      limits:
        memory: "500Mi"
      requests:
        memory: "300Mi"
    args: 
      - /bin/sh
      - -c
      - ls
   

		
